### ISSUE TITLE
Purchase a conference mic for OSU

### ISSUE THREAD

**Issue by monicacecilia** [data2health/mtip-tutorial-temp#4]
On improving communications: 
- [ ] Purchase conference room mic
- [ ] Ship to TISLAB at OSU
- [ ] Smile! :bowtie:

**Comment by tricfran** [comment]
![image](https://user-images.githubusercontent.com/24532973/45908507-c498a800-bdb1-11e8-93bc-a94d07b2b43f.png)

**Comment by tricfran** [comment]
![image](https://user-images.githubusercontent.com/24532973/45908521-d712e180-bdb1-11e8-8da1-98e5d22a39d6.png)
